### PR TITLE
SonarQube 5.x 

### PR DESCRIPTION
**Pull request by ericduran**
Adding SonarQube 5.x support.

cc @conortm @bleen we can talk more on Monday, latest versions also fixes the Drupal coding standard issue, ops is working on migrating the old instance to the latest version. Prepping for when that goes live.

### CODE REVIEW

**Comment by ericduran** [comment]
Not bad but it could use some work.

**Comment by ericduran** [comment]
The Drupal rules aren't 100% but core Drupal pass with 95% so it doesn't hurt us, but there's a decent amount missing. We can also extend the rules now, is a bit of a mess but possible, working on creating a more accurate Drupal standard for it.

**Comment by bleen** [comment]
This is the results for Flo, not for Publisher, right?

**Comment by ericduran** [comment]
Yes

**Pull request merged**
