### PR TITLE
Add stecman/symfony-console-completion to the suggested package list

### PR DESCRIPTION
**Pull request by cweagans**
stecman/symfony-console-completion adds tab completion for Flo (and any other Symfony console app (including Composer) if you install it globally). Makes the experience a lot nicer!

### CODE REVIEW

**Comment by cweagans** [comment]
hrm. A friend of mine suggested this to me, but it looks like it's not as easy as he said it was. It's still pretty easy, but it requires a code change, I guess. I'll look into this more later.

**Comment by ericduran** [comment]
@cweagans Yea we have a story for it. There's a tad bit more to do. Is it cool if we close this one and you can work on it of a fork. We shouldn't push straight to this remote.

**Comment by cweagans** [comment]
Yeah, that's fine. I edited through the web interface. Apparently, it doesn't automatically fork when you tell it to submit a PR :/

Sorry bout that.

**Comment by ericduran** [comment]
@cweagans Yea, it only forks it when you don't have commit access but I gave you access to all.

**Pull request closed without merging**
